---
# Firewall
- name: Allow all access to udp port
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items: "{{ l2tp_ipsec_server_udp_ports }}"

- name: firewall masquerade
  blockinfile:
    dest: /etc/ufw/before.rules
    insertafter: '^COMMIT\n'
    content: |
      *nat
      -A POSTROUTING -s 0.0.0.0/0 -o {{ l2tp_ipsec_server_bind_interface }} -j MASQUERADE
      COMMIT
  notify:
    - restart ufw

- name: IP forwarding
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify:
    - restart ufw